// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mySqlToIp4
IntegerVector mySqlToIp4(NumericVector x);
RcppExport SEXP Rip46_mySqlToIp4(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(mySqlToIp4(x));
    return __result;
END_RCPP
}
// hostToIp4
IntegerVector hostToIp4(CharacterVector x);
RcppExport SEXP Rip46_hostToIp4(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    __result = Rcpp::wrap(hostToIp4(x));
    return __result;
END_RCPP
}
// ip4ToHost
CharacterVector ip4ToHost(IntegerVector x);
RcppExport SEXP Rip46_ip4ToHost(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    __result = Rcpp::wrap(ip4ToHost(x));
    return __result;
END_RCPP
}
// mask
IntegerVector mask(IntegerVector x, int m);
RcppExport SEXP Rip46_mask(SEXP xSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    __result = Rcpp::wrap(mask(x, m));
    return __result;
END_RCPP
}
// classA
IntegerVector classA(IntegerVector x);
RcppExport SEXP Rip46_classA(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    __result = Rcpp::wrap(classA(x));
    return __result;
END_RCPP
}
// classB
IntegerVector classB(IntegerVector x);
RcppExport SEXP Rip46_classB(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    __result = Rcpp::wrap(classB(x));
    return __result;
END_RCPP
}
// classC
IntegerVector classC(IntegerVector x);
RcppExport SEXP Rip46_classC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    __result = Rcpp::wrap(classC(x));
    return __result;
END_RCPP
}
// hostToIp6
ComplexVector hostToIp6(CharacterVector x);
RcppExport SEXP Rip46_hostToIp6(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    __result = Rcpp::wrap(hostToIp6(x));
    return __result;
END_RCPP
}
// ip6ToHost
CharacterVector ip6ToHost(ComplexVector x);
RcppExport SEXP Rip46_ip6ToHost(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< ComplexVector >::type x(xSEXP);
    __result = Rcpp::wrap(ip6ToHost(x));
    return __result;
END_RCPP
}
