# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert MySQL ATONs to Rip4
#'
#' When you quert a MySQL db, you should call INET_ATON(ip_field) to convert to an
#' (unsigned) int.
#' 
#' Unfortunately, the RMySQL driver will convert these to doubles because not all
#' unsigned ints are representable as ints. Because doubles get normalized, we 
#' can't apply masks directly.
#'  
#' Instead, we can use signed integers.  
#'
#' @param str input numeric vector
#' @return integer format IP addresses
#'
#' @export
mySqlToIp4 <- function(x) {
    .Call('Rip46_mySqlToIp4', PACKAGE = 'Rip46', x)
}

#' Convert dotted-quad IP addresses to Rip4
#' 
#' @export
hostToIp4 <- function(x) {
    .Call('Rip46_hostToIp4', PACKAGE = 'Rip46', x)
}

#' Convert Rip4 to dotted-quad IP addresses
#' 
#' @export
ip4ToHost <- function(x) {
    .Call('Rip46_ip4ToHost', PACKAGE = 'Rip46', x)
}

#' Extract Networks from IP addresses
#'
#' @rdname network-mask
#' @export
classA <- function(x) {
    .Call('Rip46_classA', PACKAGE = 'Rip46', x)
}

#' @rdname network-mask 
#' @export
classB <- function(x) {
    .Call('Rip46_classB', PACKAGE = 'Rip46', x)
}

#' @rdname network-mask
#' @export
classC <- function(x) {
    .Call('Rip46_classC', PACKAGE = 'Rip46', x)
}

